name: CRUD OPS 
on:   
 push:   
  branches:
      - main
jobs: 
  push:
    name: push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.TEST_SERVER }}
       username: ${{ secrets.TEST_USERNAME }}
       key: ${{ secrets.TEST_KEY }}
       port: ${{ secrets.TEST_PORT }}
       script: |
        cd /home/ubuntu/CRUD/CRUDOperations/CRUDOperations
        git pull origin main
        git status
