name: CRUD  
on:   
 push:   
  branches:
      - main
jobs: 
  push:
    name: push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.TEST_SERVER }}
       username: ${{ secrets.TEST_USERNAME }}
       key: ${{ secrets.TEST_KEY }}
       port: ${{ secrets.TEST_PORT }}
       script: |
        cd /home/ubuntu/CRUD/CRUDOperations/CRUDOperations
        git pull origin main
        git status
        
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        path: /home/ubuntu/CRUD/CRUDOperations/CRUDOperations
    
    - name: Build with Maven
      run: pwd
    - name: Build with Maven
      run: mvn clean install
